default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: new_fm_development

test:
  <<: *default
  database: new_fm_test

production:
  <<: *default
  database: new_fm_production
  username: new_fm
  password: <%= ENV['NEW_FM_DATABASE_PASSWORD'] %>
